# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BettingBotInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, starting_money: int=None, starting_date: datetime=None, num_games: int=None):  # noqa: E501
        """BettingBotInput - a model defined in Swagger

        :param starting_money: The starting_money of this BettingBotInput.  # noqa: E501
        :type starting_money: int
        :param starting_date: The starting_date of this BettingBotInput.  # noqa: E501
        :type starting_date: datetime
        :param num_games: The num_games of this BettingBotInput.  # noqa: E501
        :type num_games: int
        """
        self.swagger_types = {
            'starting_money': int,
            'starting_date': datetime,
            'num_games': int
        }

        self.attribute_map = {
            'starting_money': 'starting_money',
            'starting_date': 'starting_date',
            'num_games': 'num_games'
        }

        self._starting_money = starting_money
        self._starting_date = starting_date
        self._num_games = num_games

    @classmethod
    def from_dict(cls, dikt) -> 'BettingBotInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BettingBotInput of this BettingBotInput.  # noqa: E501
        :rtype: BettingBotInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def starting_money(self) -> int:
        """Gets the starting_money of this BettingBotInput.


        :return: The starting_money of this BettingBotInput.
        :rtype: int
        """
        return self._starting_money

    @starting_money.setter
    def starting_money(self, starting_money: int):
        """Sets the starting_money of this BettingBotInput.


        :param starting_money: The starting_money of this BettingBotInput.
        :type starting_money: int
        """

        self._starting_money = starting_money

    @property
    def starting_date(self) -> datetime:
        """Gets the starting_date of this BettingBotInput.


        :return: The starting_date of this BettingBotInput.
        :rtype: datetime
        """
        return self._starting_date

    @starting_date.setter
    def starting_date(self, starting_date: datetime):
        """Sets the starting_date of this BettingBotInput.


        :param starting_date: The starting_date of this BettingBotInput.
        :type starting_date: datetime
        """

        self._starting_date = starting_date

    @property
    def num_games(self) -> int:
        """Gets the num_games of this BettingBotInput.


        :return: The num_games of this BettingBotInput.
        :rtype: int
        """
        return self._num_games

    @num_games.setter
    def num_games(self, num_games: int):
        """Sets the num_games of this BettingBotInput.


        :param num_games: The num_games of this BettingBotInput.
        :type num_games: int
        """

        self._num_games = num_games
