# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Game(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, game_id: int=None, game_date: datetime=None, home_team_id: int=None, away_team_id: int=None, season: int=None, home_team_won: bool=None, home_first: int=None, home_second: int=None, home_third: int=None, home_fourth: int=None, home_open: int=None, home_close: int=None, home_ml: int=None, home_two_h: int=None, away_first: int=None, away_second: int=None, away_third: int=None, away_fourth: int=None, away_open: int=None, away_close: int=None, away_ml: int=None, away_two_h: int=None, home_won_last: bool=None, away_won_last: bool=None):  # noqa: E501
        """Game - a model defined in Swagger

        :param game_id: The game_id of this Game.  # noqa: E501
        :type game_id: int
        :param game_date: The game_date of this Game.  # noqa: E501
        :type game_date: datetime
        :param home_team_id: The home_team_id of this Game.  # noqa: E501
        :type home_team_id: int
        :param away_team_id: The away_team_id of this Game.  # noqa: E501
        :type away_team_id: int
        :param season: The season of this Game.  # noqa: E501
        :type season: int
        :param home_team_won: The home_team_won of this Game.  # noqa: E501
        :type home_team_won: bool
        :param home_first: The home_first of this Game.  # noqa: E501
        :type home_first: int
        :param home_second: The home_second of this Game.  # noqa: E501
        :type home_second: int
        :param home_third: The home_third of this Game.  # noqa: E501
        :type home_third: int
        :param home_fourth: The home_fourth of this Game.  # noqa: E501
        :type home_fourth: int
        :param home_open: The home_open of this Game.  # noqa: E501
        :type home_open: int
        :param home_close: The home_close of this Game.  # noqa: E501
        :type home_close: int
        :param home_ml: The home_ml of this Game.  # noqa: E501
        :type home_ml: int
        :param home_two_h: The home_two_h of this Game.  # noqa: E501
        :type home_two_h: int
        :param away_first: The away_first of this Game.  # noqa: E501
        :type away_first: int
        :param away_second: The away_second of this Game.  # noqa: E501
        :type away_second: int
        :param away_third: The away_third of this Game.  # noqa: E501
        :type away_third: int
        :param away_fourth: The away_fourth of this Game.  # noqa: E501
        :type away_fourth: int
        :param away_open: The away_open of this Game.  # noqa: E501
        :type away_open: int
        :param away_close: The away_close of this Game.  # noqa: E501
        :type away_close: int
        :param away_ml: The away_ml of this Game.  # noqa: E501
        :type away_ml: int
        :param away_two_h: The away_two_h of this Game.  # noqa: E501
        :type away_two_h: int
        :param home_won_last: The home_won_last of this Game.  # noqa: E501
        :type home_won_last: bool
        :param away_won_last: The away_won_last of this Game.  # noqa: E501
        :type away_won_last: bool
        """
        self.swagger_types = {
            'game_id': int,
            'game_date': datetime,
            'home_team_id': int,
            'away_team_id': int,
            'season': int,
            'home_team_won': bool,
            'home_first': int,
            'home_second': int,
            'home_third': int,
            'home_fourth': int,
            'home_open': int,
            'home_close': int,
            'home_ml': int,
            'home_two_h': int,
            'away_first': int,
            'away_second': int,
            'away_third': int,
            'away_fourth': int,
            'away_open': int,
            'away_close': int,
            'away_ml': int,
            'away_two_h': int,
            'home_won_last': bool,
            'away_won_last': bool
        }

        self.attribute_map = {
            'game_id': 'game_id',
            'game_date': 'game_date',
            'home_team_id': 'home_team_id',
            'away_team_id': 'away_team_id',
            'season': 'season',
            'home_team_won': 'home_team_won',
            'home_first': 'home_first',
            'home_second': 'home_second',
            'home_third': 'home_third',
            'home_fourth': 'home_fourth',
            'home_open': 'home_open',
            'home_close': 'home_close',
            'home_ml': 'home_ml',
            'home_two_h': 'home_two_h',
            'away_first': 'away_first',
            'away_second': 'away_second',
            'away_third': 'away_third',
            'away_fourth': 'away_fourth',
            'away_open': 'away_open',
            'away_close': 'away_close',
            'away_ml': 'away_ml',
            'away_two_h': 'away_two_h',
            'home_won_last': 'home_won_last',
            'away_won_last': 'away_won_last'
        }

        self._game_id = game_id
        self._game_date = game_date
        self._home_team_id = home_team_id
        self._away_team_id = away_team_id
        self._season = season
        self._home_team_won = home_team_won
        self._home_first = home_first
        self._home_second = home_second
        self._home_third = home_third
        self._home_fourth = home_fourth
        self._home_open = home_open
        self._home_close = home_close
        self._home_ml = home_ml
        self._home_two_h = home_two_h
        self._away_first = away_first
        self._away_second = away_second
        self._away_third = away_third
        self._away_fourth = away_fourth
        self._away_open = away_open
        self._away_close = away_close
        self._away_ml = away_ml
        self._away_two_h = away_two_h
        self._home_won_last = home_won_last
        self._away_won_last = away_won_last

    @classmethod
    def from_dict(cls, dikt) -> 'Game':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Game of this Game.  # noqa: E501
        :rtype: Game
        """
        return util.deserialize_model(dikt, cls)

    @property
    def game_id(self) -> int:
        """Gets the game_id of this Game.


        :return: The game_id of this Game.
        :rtype: int
        """
        return self._game_id

    @game_id.setter
    def game_id(self, game_id: int):
        """Sets the game_id of this Game.


        :param game_id: The game_id of this Game.
        :type game_id: int
        """

        self._game_id = game_id

    @property
    def game_date(self) -> datetime:
        """Gets the game_date of this Game.


        :return: The game_date of this Game.
        :rtype: datetime
        """
        return self._game_date

    @game_date.setter
    def game_date(self, game_date: datetime):
        """Sets the game_date of this Game.


        :param game_date: The game_date of this Game.
        :type game_date: datetime
        """

        self._game_date = game_date

    @property
    def home_team_id(self) -> int:
        """Gets the home_team_id of this Game.


        :return: The home_team_id of this Game.
        :rtype: int
        """
        return self._home_team_id

    @home_team_id.setter
    def home_team_id(self, home_team_id: int):
        """Sets the home_team_id of this Game.


        :param home_team_id: The home_team_id of this Game.
        :type home_team_id: int
        """

        self._home_team_id = home_team_id

    @property
    def away_team_id(self) -> int:
        """Gets the away_team_id of this Game.


        :return: The away_team_id of this Game.
        :rtype: int
        """
        return self._away_team_id

    @away_team_id.setter
    def away_team_id(self, away_team_id: int):
        """Sets the away_team_id of this Game.


        :param away_team_id: The away_team_id of this Game.
        :type away_team_id: int
        """

        self._away_team_id = away_team_id

    @property
    def season(self) -> int:
        """Gets the season of this Game.


        :return: The season of this Game.
        :rtype: int
        """
        return self._season

    @season.setter
    def season(self, season: int):
        """Sets the season of this Game.


        :param season: The season of this Game.
        :type season: int
        """

        self._season = season

    @property
    def home_team_won(self) -> bool:
        """Gets the home_team_won of this Game.


        :return: The home_team_won of this Game.
        :rtype: bool
        """
        return self._home_team_won

    @home_team_won.setter
    def home_team_won(self, home_team_won: bool):
        """Sets the home_team_won of this Game.


        :param home_team_won: The home_team_won of this Game.
        :type home_team_won: bool
        """

        self._home_team_won = home_team_won

    @property
    def home_first(self) -> int:
        """Gets the home_first of this Game.


        :return: The home_first of this Game.
        :rtype: int
        """
        return self._home_first

    @home_first.setter
    def home_first(self, home_first: int):
        """Sets the home_first of this Game.


        :param home_first: The home_first of this Game.
        :type home_first: int
        """

        self._home_first = home_first

    @property
    def home_second(self) -> int:
        """Gets the home_second of this Game.


        :return: The home_second of this Game.
        :rtype: int
        """
        return self._home_second

    @home_second.setter
    def home_second(self, home_second: int):
        """Sets the home_second of this Game.


        :param home_second: The home_second of this Game.
        :type home_second: int
        """

        self._home_second = home_second

    @property
    def home_third(self) -> int:
        """Gets the home_third of this Game.


        :return: The home_third of this Game.
        :rtype: int
        """
        return self._home_third

    @home_third.setter
    def home_third(self, home_third: int):
        """Sets the home_third of this Game.


        :param home_third: The home_third of this Game.
        :type home_third: int
        """

        self._home_third = home_third

    @property
    def home_fourth(self) -> int:
        """Gets the home_fourth of this Game.


        :return: The home_fourth of this Game.
        :rtype: int
        """
        return self._home_fourth

    @home_fourth.setter
    def home_fourth(self, home_fourth: int):
        """Sets the home_fourth of this Game.


        :param home_fourth: The home_fourth of this Game.
        :type home_fourth: int
        """

        self._home_fourth = home_fourth

    @property
    def home_open(self) -> int:
        """Gets the home_open of this Game.


        :return: The home_open of this Game.
        :rtype: int
        """
        return self._home_open

    @home_open.setter
    def home_open(self, home_open: int):
        """Sets the home_open of this Game.


        :param home_open: The home_open of this Game.
        :type home_open: int
        """

        self._home_open = home_open

    @property
    def home_close(self) -> int:
        """Gets the home_close of this Game.


        :return: The home_close of this Game.
        :rtype: int
        """
        return self._home_close

    @home_close.setter
    def home_close(self, home_close: int):
        """Sets the home_close of this Game.


        :param home_close: The home_close of this Game.
        :type home_close: int
        """

        self._home_close = home_close

    @property
    def home_ml(self) -> int:
        """Gets the home_ml of this Game.


        :return: The home_ml of this Game.
        :rtype: int
        """
        return self._home_ml

    @home_ml.setter
    def home_ml(self, home_ml: int):
        """Sets the home_ml of this Game.


        :param home_ml: The home_ml of this Game.
        :type home_ml: int
        """

        self._home_ml = home_ml

    @property
    def home_two_h(self) -> int:
        """Gets the home_two_h of this Game.


        :return: The home_two_h of this Game.
        :rtype: int
        """
        return self._home_two_h

    @home_two_h.setter
    def home_two_h(self, home_two_h: int):
        """Sets the home_two_h of this Game.


        :param home_two_h: The home_two_h of this Game.
        :type home_two_h: int
        """

        self._home_two_h = home_two_h

    @property
    def away_first(self) -> int:
        """Gets the away_first of this Game.


        :return: The away_first of this Game.
        :rtype: int
        """
        return self._away_first

    @away_first.setter
    def away_first(self, away_first: int):
        """Sets the away_first of this Game.


        :param away_first: The away_first of this Game.
        :type away_first: int
        """

        self._away_first = away_first

    @property
    def away_second(self) -> int:
        """Gets the away_second of this Game.


        :return: The away_second of this Game.
        :rtype: int
        """
        return self._away_second

    @away_second.setter
    def away_second(self, away_second: int):
        """Sets the away_second of this Game.


        :param away_second: The away_second of this Game.
        :type away_second: int
        """

        self._away_second = away_second

    @property
    def away_third(self) -> int:
        """Gets the away_third of this Game.


        :return: The away_third of this Game.
        :rtype: int
        """
        return self._away_third

    @away_third.setter
    def away_third(self, away_third: int):
        """Sets the away_third of this Game.


        :param away_third: The away_third of this Game.
        :type away_third: int
        """

        self._away_third = away_third

    @property
    def away_fourth(self) -> int:
        """Gets the away_fourth of this Game.


        :return: The away_fourth of this Game.
        :rtype: int
        """
        return self._away_fourth

    @away_fourth.setter
    def away_fourth(self, away_fourth: int):
        """Sets the away_fourth of this Game.


        :param away_fourth: The away_fourth of this Game.
        :type away_fourth: int
        """

        self._away_fourth = away_fourth

    @property
    def away_open(self) -> int:
        """Gets the away_open of this Game.


        :return: The away_open of this Game.
        :rtype: int
        """
        return self._away_open

    @away_open.setter
    def away_open(self, away_open: int):
        """Sets the away_open of this Game.


        :param away_open: The away_open of this Game.
        :type away_open: int
        """

        self._away_open = away_open

    @property
    def away_close(self) -> int:
        """Gets the away_close of this Game.


        :return: The away_close of this Game.
        :rtype: int
        """
        return self._away_close

    @away_close.setter
    def away_close(self, away_close: int):
        """Sets the away_close of this Game.


        :param away_close: The away_close of this Game.
        :type away_close: int
        """

        self._away_close = away_close

    @property
    def away_ml(self) -> int:
        """Gets the away_ml of this Game.


        :return: The away_ml of this Game.
        :rtype: int
        """
        return self._away_ml

    @away_ml.setter
    def away_ml(self, away_ml: int):
        """Sets the away_ml of this Game.


        :param away_ml: The away_ml of this Game.
        :type away_ml: int
        """

        self._away_ml = away_ml

    @property
    def away_two_h(self) -> int:
        """Gets the away_two_h of this Game.


        :return: The away_two_h of this Game.
        :rtype: int
        """
        return self._away_two_h

    @away_two_h.setter
    def away_two_h(self, away_two_h: int):
        """Sets the away_two_h of this Game.


        :param away_two_h: The away_two_h of this Game.
        :type away_two_h: int
        """

        self._away_two_h = away_two_h

    @property
    def home_won_last(self) -> bool:
        """Gets the home_won_last of this Game.


        :return: The home_won_last of this Game.
        :rtype: bool
        """
        return self._home_won_last

    @home_won_last.setter
    def home_won_last(self, home_won_last: bool):
        """Sets the home_won_last of this Game.


        :param home_won_last: The home_won_last of this Game.
        :type home_won_last: bool
        """

        self._home_won_last = home_won_last

    @property
    def away_won_last(self) -> bool:
        """Gets the away_won_last of this Game.


        :return: The away_won_last of this Game.
        :rtype: bool
        """
        return self._away_won_last

    @away_won_last.setter
    def away_won_last(self, away_won_last: bool):
        """Sets the away_won_last of this Game.


        :param away_won_last: The away_won_last of this Game.
        :type away_won_last: bool
        """

        self._away_won_last = away_won_last
