# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NerualNetInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, _date: datetime=None, tweet: str=None):  # noqa: E501
        """NerualNetInput - a model defined in Swagger

        :param _date: The _date of this NerualNetInput.  # noqa: E501
        :type _date: datetime
        :param tweet: The tweet of this NerualNetInput.  # noqa: E501
        :type tweet: str
        """
        self.swagger_types = {
            '_date': datetime,
            'tweet': str
        }

        self.attribute_map = {
            '_date': 'date',
            'tweet': 'tweet'
        }

        self.__date = _date
        self._tweet = tweet

    @classmethod
    def from_dict(cls, dikt) -> 'NerualNetInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NerualNetInput of this NerualNetInput.  # noqa: E501
        :rtype: NerualNetInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> datetime:
        """Gets the _date of this NerualNetInput.


        :return: The _date of this NerualNetInput.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this NerualNetInput.


        :param _date: The _date of this NerualNetInput.
        :type _date: datetime
        """

        self.__date = _date

    @property
    def tweet(self) -> str:
        """Gets the tweet of this NerualNetInput.


        :return: The tweet of this NerualNetInput.
        :rtype: str
        """
        return self._tweet

    @tweet.setter
    def tweet(self, tweet: str):
        """Sets the tweet of this NerualNetInput.


        :param tweet: The tweet of this NerualNetInput.
        :type tweet: str
        """

        self._tweet = tweet
