# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ClusterInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, season: int=None, player_ids: List[int]=None):  # noqa: E501
        """ClusterInput - a model defined in Swagger

        :param season: The season of this ClusterInput.  # noqa: E501
        :type season: int
        :param player_ids: The player_ids of this ClusterInput.  # noqa: E501
        :type player_ids: List[int]
        """
        self.swagger_types = {
            'season': int,
            'player_ids': List[int]
        }

        self.attribute_map = {
            'season': 'season',
            'player_ids': 'player_ids'
        }

        self._season = season
        self._player_ids = player_ids

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterInput of this ClusterInput.  # noqa: E501
        :rtype: ClusterInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def season(self) -> int:
        """Gets the season of this ClusterInput.


        :return: The season of this ClusterInput.
        :rtype: int
        """
        return self._season

    @season.setter
    def season(self, season: int):
        """Sets the season of this ClusterInput.


        :param season: The season of this ClusterInput.
        :type season: int
        """

        self._season = season

    @property
    def player_ids(self) -> List[int]:
        """Gets the player_ids of this ClusterInput.


        :return: The player_ids of this ClusterInput.
        :rtype: List[int]
        """
        return self._player_ids

    @player_ids.setter
    def player_ids(self, player_ids: List[int]):
        """Sets the player_ids of this ClusterInput.


        :param player_ids: The player_ids of this ClusterInput.
        :type player_ids: List[int]
        """

        self._player_ids = player_ids
