# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SeasonStatistics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, games_played: int=None, avg_seconds_played: float=None, avg_field_goals_made: float=None, avg_field_goals_attempted: float=None, avg_three_pointers_made: float=None, avg_three_pointers_attempted: float=None, avg_free_throws_made: float=None, avg_free_throws_attempted: float=None, avg_offensive_rebounds: float=None, avg_defensive_rebounds: float=None, avg_assists: float=None, avg_steals: float=None, avg_blocked_shots: float=None, avg_turnovers: float=None, avg_personal_fouls: float=None, avg_points: float=None, avg_plus_minus: float=None):  # noqa: E501
        """SeasonStatistics - a model defined in Swagger

        :param games_played: The games_played of this SeasonStatistics.  # noqa: E501
        :type games_played: int
        :param avg_seconds_played: The avg_seconds_played of this SeasonStatistics.  # noqa: E501
        :type avg_seconds_played: float
        :param avg_field_goals_made: The avg_field_goals_made of this SeasonStatistics.  # noqa: E501
        :type avg_field_goals_made: float
        :param avg_field_goals_attempted: The avg_field_goals_attempted of this SeasonStatistics.  # noqa: E501
        :type avg_field_goals_attempted: float
        :param avg_three_pointers_made: The avg_three_pointers_made of this SeasonStatistics.  # noqa: E501
        :type avg_three_pointers_made: float
        :param avg_three_pointers_attempted: The avg_three_pointers_attempted of this SeasonStatistics.  # noqa: E501
        :type avg_three_pointers_attempted: float
        :param avg_free_throws_made: The avg_free_throws_made of this SeasonStatistics.  # noqa: E501
        :type avg_free_throws_made: float
        :param avg_free_throws_attempted: The avg_free_throws_attempted of this SeasonStatistics.  # noqa: E501
        :type avg_free_throws_attempted: float
        :param avg_offensive_rebounds: The avg_offensive_rebounds of this SeasonStatistics.  # noqa: E501
        :type avg_offensive_rebounds: float
        :param avg_defensive_rebounds: The avg_defensive_rebounds of this SeasonStatistics.  # noqa: E501
        :type avg_defensive_rebounds: float
        :param avg_assists: The avg_assists of this SeasonStatistics.  # noqa: E501
        :type avg_assists: float
        :param avg_steals: The avg_steals of this SeasonStatistics.  # noqa: E501
        :type avg_steals: float
        :param avg_blocked_shots: The avg_blocked_shots of this SeasonStatistics.  # noqa: E501
        :type avg_blocked_shots: float
        :param avg_turnovers: The avg_turnovers of this SeasonStatistics.  # noqa: E501
        :type avg_turnovers: float
        :param avg_personal_fouls: The avg_personal_fouls of this SeasonStatistics.  # noqa: E501
        :type avg_personal_fouls: float
        :param avg_points: The avg_points of this SeasonStatistics.  # noqa: E501
        :type avg_points: float
        :param avg_plus_minus: The avg_plus_minus of this SeasonStatistics.  # noqa: E501
        :type avg_plus_minus: float
        """
        self.swagger_types = {
            'games_played': int,
            'avg_seconds_played': float,
            'avg_field_goals_made': float,
            'avg_field_goals_attempted': float,
            'avg_three_pointers_made': float,
            'avg_three_pointers_attempted': float,
            'avg_free_throws_made': float,
            'avg_free_throws_attempted': float,
            'avg_offensive_rebounds': float,
            'avg_defensive_rebounds': float,
            'avg_assists': float,
            'avg_steals': float,
            'avg_blocked_shots': float,
            'avg_turnovers': float,
            'avg_personal_fouls': float,
            'avg_points': float,
            'avg_plus_minus': float
        }

        self.attribute_map = {
            'games_played': 'games_played',
            'avg_seconds_played': 'avg_seconds_played',
            'avg_field_goals_made': 'avg_field_goals_made',
            'avg_field_goals_attempted': 'avg_field_goals_attempted',
            'avg_three_pointers_made': 'avg_three_pointers_made',
            'avg_three_pointers_attempted': 'avg_three_pointers_attempted',
            'avg_free_throws_made': 'avg_free_throws_made',
            'avg_free_throws_attempted': 'avg_free_throws_attempted',
            'avg_offensive_rebounds': 'avg_offensive_rebounds',
            'avg_defensive_rebounds': 'avg_defensive_rebounds',
            'avg_assists': 'avg_assists',
            'avg_steals': 'avg_steals',
            'avg_blocked_shots': 'avg_blocked_shots',
            'avg_turnovers': 'avg_turnovers',
            'avg_personal_fouls': 'avg_personal_fouls',
            'avg_points': 'avg_points',
            'avg_plus_minus': 'avg_plus_minus'
        }

        self._games_played = games_played
        self._avg_seconds_played = avg_seconds_played
        self._avg_field_goals_made = avg_field_goals_made
        self._avg_field_goals_attempted = avg_field_goals_attempted
        self._avg_three_pointers_made = avg_three_pointers_made
        self._avg_three_pointers_attempted = avg_three_pointers_attempted
        self._avg_free_throws_made = avg_free_throws_made
        self._avg_free_throws_attempted = avg_free_throws_attempted
        self._avg_offensive_rebounds = avg_offensive_rebounds
        self._avg_defensive_rebounds = avg_defensive_rebounds
        self._avg_assists = avg_assists
        self._avg_steals = avg_steals
        self._avg_blocked_shots = avg_blocked_shots
        self._avg_turnovers = avg_turnovers
        self._avg_personal_fouls = avg_personal_fouls
        self._avg_points = avg_points
        self._avg_plus_minus = avg_plus_minus

    @classmethod
    def from_dict(cls, dikt) -> 'SeasonStatistics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SeasonStatistics of this SeasonStatistics.  # noqa: E501
        :rtype: SeasonStatistics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def games_played(self) -> int:
        """Gets the games_played of this SeasonStatistics.


        :return: The games_played of this SeasonStatistics.
        :rtype: int
        """
        return self._games_played

    @games_played.setter
    def games_played(self, games_played: int):
        """Sets the games_played of this SeasonStatistics.


        :param games_played: The games_played of this SeasonStatistics.
        :type games_played: int
        """

        self._games_played = games_played

    @property
    def avg_seconds_played(self) -> float:
        """Gets the avg_seconds_played of this SeasonStatistics.


        :return: The avg_seconds_played of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_seconds_played

    @avg_seconds_played.setter
    def avg_seconds_played(self, avg_seconds_played: float):
        """Sets the avg_seconds_played of this SeasonStatistics.


        :param avg_seconds_played: The avg_seconds_played of this SeasonStatistics.
        :type avg_seconds_played: float
        """

        self._avg_seconds_played = avg_seconds_played

    @property
    def avg_field_goals_made(self) -> float:
        """Gets the avg_field_goals_made of this SeasonStatistics.


        :return: The avg_field_goals_made of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_field_goals_made

    @avg_field_goals_made.setter
    def avg_field_goals_made(self, avg_field_goals_made: float):
        """Sets the avg_field_goals_made of this SeasonStatistics.


        :param avg_field_goals_made: The avg_field_goals_made of this SeasonStatistics.
        :type avg_field_goals_made: float
        """

        self._avg_field_goals_made = avg_field_goals_made

    @property
    def avg_field_goals_attempted(self) -> float:
        """Gets the avg_field_goals_attempted of this SeasonStatistics.


        :return: The avg_field_goals_attempted of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_field_goals_attempted

    @avg_field_goals_attempted.setter
    def avg_field_goals_attempted(self, avg_field_goals_attempted: float):
        """Sets the avg_field_goals_attempted of this SeasonStatistics.


        :param avg_field_goals_attempted: The avg_field_goals_attempted of this SeasonStatistics.
        :type avg_field_goals_attempted: float
        """

        self._avg_field_goals_attempted = avg_field_goals_attempted

    @property
    def avg_three_pointers_made(self) -> float:
        """Gets the avg_three_pointers_made of this SeasonStatistics.


        :return: The avg_three_pointers_made of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_three_pointers_made

    @avg_three_pointers_made.setter
    def avg_three_pointers_made(self, avg_three_pointers_made: float):
        """Sets the avg_three_pointers_made of this SeasonStatistics.


        :param avg_three_pointers_made: The avg_three_pointers_made of this SeasonStatistics.
        :type avg_three_pointers_made: float
        """

        self._avg_three_pointers_made = avg_three_pointers_made

    @property
    def avg_three_pointers_attempted(self) -> float:
        """Gets the avg_three_pointers_attempted of this SeasonStatistics.


        :return: The avg_three_pointers_attempted of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_three_pointers_attempted

    @avg_three_pointers_attempted.setter
    def avg_three_pointers_attempted(self, avg_three_pointers_attempted: float):
        """Sets the avg_three_pointers_attempted of this SeasonStatistics.


        :param avg_three_pointers_attempted: The avg_three_pointers_attempted of this SeasonStatistics.
        :type avg_three_pointers_attempted: float
        """

        self._avg_three_pointers_attempted = avg_three_pointers_attempted

    @property
    def avg_free_throws_made(self) -> float:
        """Gets the avg_free_throws_made of this SeasonStatistics.


        :return: The avg_free_throws_made of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_free_throws_made

    @avg_free_throws_made.setter
    def avg_free_throws_made(self, avg_free_throws_made: float):
        """Sets the avg_free_throws_made of this SeasonStatistics.


        :param avg_free_throws_made: The avg_free_throws_made of this SeasonStatistics.
        :type avg_free_throws_made: float
        """

        self._avg_free_throws_made = avg_free_throws_made

    @property
    def avg_free_throws_attempted(self) -> float:
        """Gets the avg_free_throws_attempted of this SeasonStatistics.


        :return: The avg_free_throws_attempted of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_free_throws_attempted

    @avg_free_throws_attempted.setter
    def avg_free_throws_attempted(self, avg_free_throws_attempted: float):
        """Sets the avg_free_throws_attempted of this SeasonStatistics.


        :param avg_free_throws_attempted: The avg_free_throws_attempted of this SeasonStatistics.
        :type avg_free_throws_attempted: float
        """

        self._avg_free_throws_attempted = avg_free_throws_attempted

    @property
    def avg_offensive_rebounds(self) -> float:
        """Gets the avg_offensive_rebounds of this SeasonStatistics.


        :return: The avg_offensive_rebounds of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_offensive_rebounds

    @avg_offensive_rebounds.setter
    def avg_offensive_rebounds(self, avg_offensive_rebounds: float):
        """Sets the avg_offensive_rebounds of this SeasonStatistics.


        :param avg_offensive_rebounds: The avg_offensive_rebounds of this SeasonStatistics.
        :type avg_offensive_rebounds: float
        """

        self._avg_offensive_rebounds = avg_offensive_rebounds

    @property
    def avg_defensive_rebounds(self) -> float:
        """Gets the avg_defensive_rebounds of this SeasonStatistics.


        :return: The avg_defensive_rebounds of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_defensive_rebounds

    @avg_defensive_rebounds.setter
    def avg_defensive_rebounds(self, avg_defensive_rebounds: float):
        """Sets the avg_defensive_rebounds of this SeasonStatistics.


        :param avg_defensive_rebounds: The avg_defensive_rebounds of this SeasonStatistics.
        :type avg_defensive_rebounds: float
        """

        self._avg_defensive_rebounds = avg_defensive_rebounds

    @property
    def avg_assists(self) -> float:
        """Gets the avg_assists of this SeasonStatistics.


        :return: The avg_assists of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_assists

    @avg_assists.setter
    def avg_assists(self, avg_assists: float):
        """Sets the avg_assists of this SeasonStatistics.


        :param avg_assists: The avg_assists of this SeasonStatistics.
        :type avg_assists: float
        """

        self._avg_assists = avg_assists

    @property
    def avg_steals(self) -> float:
        """Gets the avg_steals of this SeasonStatistics.


        :return: The avg_steals of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_steals

    @avg_steals.setter
    def avg_steals(self, avg_steals: float):
        """Sets the avg_steals of this SeasonStatistics.


        :param avg_steals: The avg_steals of this SeasonStatistics.
        :type avg_steals: float
        """

        self._avg_steals = avg_steals

    @property
    def avg_blocked_shots(self) -> float:
        """Gets the avg_blocked_shots of this SeasonStatistics.


        :return: The avg_blocked_shots of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_blocked_shots

    @avg_blocked_shots.setter
    def avg_blocked_shots(self, avg_blocked_shots: float):
        """Sets the avg_blocked_shots of this SeasonStatistics.


        :param avg_blocked_shots: The avg_blocked_shots of this SeasonStatistics.
        :type avg_blocked_shots: float
        """

        self._avg_blocked_shots = avg_blocked_shots

    @property
    def avg_turnovers(self) -> float:
        """Gets the avg_turnovers of this SeasonStatistics.


        :return: The avg_turnovers of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_turnovers

    @avg_turnovers.setter
    def avg_turnovers(self, avg_turnovers: float):
        """Sets the avg_turnovers of this SeasonStatistics.


        :param avg_turnovers: The avg_turnovers of this SeasonStatistics.
        :type avg_turnovers: float
        """

        self._avg_turnovers = avg_turnovers

    @property
    def avg_personal_fouls(self) -> float:
        """Gets the avg_personal_fouls of this SeasonStatistics.


        :return: The avg_personal_fouls of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_personal_fouls

    @avg_personal_fouls.setter
    def avg_personal_fouls(self, avg_personal_fouls: float):
        """Sets the avg_personal_fouls of this SeasonStatistics.


        :param avg_personal_fouls: The avg_personal_fouls of this SeasonStatistics.
        :type avg_personal_fouls: float
        """

        self._avg_personal_fouls = avg_personal_fouls

    @property
    def avg_points(self) -> float:
        """Gets the avg_points of this SeasonStatistics.


        :return: The avg_points of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_points

    @avg_points.setter
    def avg_points(self, avg_points: float):
        """Sets the avg_points of this SeasonStatistics.


        :param avg_points: The avg_points of this SeasonStatistics.
        :type avg_points: float
        """

        self._avg_points = avg_points

    @property
    def avg_plus_minus(self) -> float:
        """Gets the avg_plus_minus of this SeasonStatistics.


        :return: The avg_plus_minus of this SeasonStatistics.
        :rtype: float
        """
        return self._avg_plus_minus

    @avg_plus_minus.setter
    def avg_plus_minus(self, avg_plus_minus: float):
        """Sets the avg_plus_minus of this SeasonStatistics.


        :param avg_plus_minus: The avg_plus_minus of this SeasonStatistics.
        :type avg_plus_minus: float
        """

        self._avg_plus_minus = avg_plus_minus
